"""add foreign_keys to appearance

Revision ID: 7e84b36281a1
Revises: 0159c5f17394
Create Date: 2024-04-03 09:53:00.450795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e84b36281a1'
down_revision = '0159c5f17394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('episode_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appearances_episode_id_episodes'), 'episodes', ['episode_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_appearances_guest_id_guests'), 'guests', ['guest_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appearances_guest_id_guests'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_appearances_episode_id_episodes'), type_='foreignkey')
        batch_op.drop_column('episode_id')
        batch_op.drop_column('guest_id')

    # ### end Alembic commands ###
